
---
# setup_docker_swarm.yml
- name: Setup Docker Swarm
  hosts: all
  become: true
  tasks:
    - name: Initialize Swarm on the manager
      shell: |
        docker swarm init --advertise-addr {{ ansible_host }}
      when: inventory_hostname == 'ansible-Con-troller'

    - name: Retrieve manager token
      command: docker swarm join-token manager -q
      register: manager_token
      delegate_to: ansible-Con-troller
      when: inventory_hostname == 'ansible-Con-troller'

    - name: Retrieve worker token
      command: docker swarm join-token worker -q
      register: worker_token
      delegate_to: ansible-Con-troller
      when: inventory_hostname == 'ansible-Con-troller'

    - name: Join managers to the swarm
      shell: |
        docker swarm join --token {{ manager_token.stdout }} {{ hostvars['ansible-Con-troller'].ansible_host }}:2377
      when: inventory_hostname in ['Main-Con-troller', 'Main-Con-sole', 'Main-Con-nection']

    - name: Join workers to the swarm
      shell: |
        docker swarm join --token {{ worker_token.stdout }} {{ hostvars['ansible-Con-troller'].ansible_host }}:2377
      when: inventory_hostname in ['Swarm-Client-01', 'Swarm-Client-02']
